<?php

namespace App\Service;

use App\Entity\Invite;
use App\Entity\InviteStatus;
use App\Entity\User;
use App\Repository\InviteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * Owns invite creation, delivery and redemption.
 *
 * Only the SHA-256 of a token is persisted; the raw token exists in the email
 * and, transiently, in lastToken() for the request that created it. When invites
 * later become user-initiated with admin approval, the policy change lands here:
 * create() gains a pending status and send() moves behind approval.
 */
class InviteService
{
    private const TOKEN_BYTES = 32;
    private const LIFETIME = '+14 days';

    private ?string $lastToken = null;

    public function __construct(
        private EntityManagerInterface $em,
        private InviteRepository $inviteRepository,
        private MailerInterface $mailer,
        private UrlGeneratorInterface $urlGenerator,
        private LoggerInterface $logger,
        private string $mailFrom,
        private string $mailFromName,
    ) {
    }

    public function create(string $email, User $createdBy): Invite
    {
        $invite = new Invite();
        $invite->setEmail($email);
        $invite->setCreatedBy($createdBy);
        $invite->setTokenHash($this->issueToken());
        $invite->setExpiresAt(new \DateTimeImmutable(self::LIFETIME));

        $this->em->persist($invite);
        $this->em->flush();

        return $invite;
    }

    public function resend(Invite $invite): void
    {
        $invite->setTokenHash($this->issueToken());
        $invite->setExpiresAt(new \DateTimeImmutable(self::LIFETIME));
        $invite->setStatus(InviteStatus::Sent);
        $this->em->flush();
    }

    public function revoke(Invite $invite): void
    {
        $invite->setStatus(InviteStatus::Revoked);
        $this->em->flush();
    }

    /** The raw token generated by the most recent create() or resend(). */
    public function lastToken(): ?string
    {
        return $this->lastToken;
    }

    public function findRedeemable(string $rawToken): ?Invite
    {
        $invite = $this->inviteRepository->findByTokenHash(hash('sha256', $rawToken));

        return ($invite && $invite->isRedeemable()) ? $invite : null;
    }

    public function accept(Invite $invite, string $username, string $password): User
    {
        if (!$invite->isRedeemable()) {
            throw new InviteNotRedeemableException('This invite is no longer redeemable.');
        }

        $user = new User();
        $user->setUsername($username);
        $user->setEmail($invite->getEmail());
        $user->setPassword(password_hash($password, PASSWORD_BCRYPT));
        $user->setInvitedBy($invite->getCreatedBy());
        $this->em->persist($user);

        $invite->setStatus(InviteStatus::Accepted);
        $invite->setAcceptedAt(new \DateTimeImmutable());
        $invite->setAcceptedUser($user);

        $this->em->flush();

        return $user;
    }

    public function urlFor(string $rawToken): string
    {
        return $this->urlGenerator->generate(
            'app_invite_accept',
            ['token' => $rawToken],
            UrlGeneratorInterface::ABSOLUTE_URL,
        );
    }

    /** Returns false when the transport rejected the message. */
    public function send(Invite $invite, string $rawToken): bool
    {
        $email = (new TemplatedEmail())
            ->from(new Address($this->mailFrom, $this->mailFromName))
            ->to($invite->getEmail())
            ->subject('You have been invited to Spread Dread')
            ->htmlTemplate('email/invite.html.twig')
            ->textTemplate('email/invite.txt.twig')
            ->context([
                'url' => $this->urlFor($rawToken),
                'expiresAt' => $invite->getExpiresAt(),
            ]);

        try {
            $this->mailer->send($email);
            return true;
        } catch (TransportExceptionInterface $e) {
            // The invite row survives so the admin can copy the link by hand.
            $this->logger->error('Invite email failed to send', [
                'invite_id' => $invite->getId(),
                'error' => $e->getMessage(),
            ]);
            return false;
        }
    }

    private function issueToken(): string
    {
        $this->lastToken = bin2hex(random_bytes(self::TOKEN_BYTES));
        return hash('sha256', $this->lastToken);
    }
}
